project: 
  type: website

website:
  title: "2023 GEDI/ICESAT-2 Workshop"
  site-url: https://nasa-openscapes.github.io/2023-ssc
  repo-url: https://github.com/NASA-Openscapes/2023-ssc
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "NASA Openscapes (2023). Espacio y Sostenibilidad Colloqium, Guadalajara, Mexico"
 
  navbar: 
    background: primary
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/NASA-Openscapes/2023-ssc
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: https://raw.githubusercontent.com/NASA-Openscapes/media/main/images/scc/espacio-logo.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - section: "Welcome / Bienvenidos"
          contents:
            - index.md
            - tutorials/prerequisites.md 
            - tutorials/schedule.md
        - section: "Cloud Computing"
          contents: 
            - href: tutorials/cloud/cloud-paradigm.md
              text: "NASA and the Cloud"
            - href: tutorials/jupyterhub_demo/jupyterhub_demo.ipynb
              text: "CryoCloud"
        - section: "Search and Access NASA Earthdata"
          contents: 
            - href: tutorials/data-access/earthdata-search.md
              text: "Earthdata Search"
        - section: "NASA ICESat-2 Mission"
          contents: 
            - href: tutorials/data-access/index.ipynb
              text: "earthaccess for data discovery and access"
            - href: tutorials/data-access/icepyx.ipynb
              text: "Icepyx for data discovery and access"
        - section: "NASA GEDI Mission"
          contents: 
            - tutorials/index.md
            - href: tutorials/science/gedi-l4a-agbd.ipynb
              text: "GEDI Level 4A Data"
            - href: tutorials/science/gedi-data-ssc23.ipynb
              text: "GEDI Level 2B V002 Data"

            
          
format:
  html:
    theme:
      light: sandstone
      dark: [sandstone, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
